Transmit
cornellnexus/src pull request #144
Opened 2023-10-21 17:31 UTC by span1012

## References
[](https://github.com/cornellnexus/src/blob/7dbc46cc7159a8930abc17508cc850f69c8e155c/engine/packet.md)

## Summary
### TLDR: Connected data gathered from the rest of the files to define the gather_info function as defined in packet.md and added the reference for most of the attributes.

### Description

- Implemented all of the attributes in "ultrasonic" and "wheel_motors
- Implemented partially the attributes in "metrics" and "battery"
- Used the packet.md file to determine what attributes needed to be included and primarily used the robot_state and mission_state files for definition
- Some of the attributes cannot be fully defined as of yet, those waiting for commits have been committed outand those partially defined have temporary values and commented TODOs added for the incomplete attributes

## Test Plan

N/A

## Other
To-Dos:
- Waiting on commits for "cams" and "breakbeams"
- battery: "time_until_recharge", low_power_mode": TODO
- "global_coord" for metrics/"goal_loc" and metrics/"state" (these were commented out)
- metrics: "eta_to_base", "goal_nodes_completed", "eta_complete": TODO

2023-10-21 20:04 UTC, AC408 approved these changes
Looks good, make sure to address merge conflicts

2023-10-24 19:42 UTC, Shreya1233 commented on engine/transmittor.py
> +        self.gather_info()
since the gather_info function's name was changed to rmi, you'd have to change the name here as well.

2023-10-25 21:02 UTC, Shreya1233 commented on engine/transmittor.py
> +    def rmi(self):
This function has some syntax errors - could you run it in chatgpt and ask it to fix it for you.

2023-10-25 21:02 UTC, Shreya1233 commented on engine/transmittor.py
> +                "time_until_recharge": 00:00:00 #TODO,
the comma should be before the comment

2023-10-25 21:03 UTC, Shreya1233 commented on engine/transmittor.py
> +                    "global_coord": self.robot_state.goal_location  #TODO,
same thing with the comma should be before the TODO comment here

2023-10-25 21:33 UTC, Shreya1233 commented on engine/transmittor.py
> +                "eta_complete": 00:00:00 #TODO
could you also ETA of next node? It's currently a TODO so just 00:00:00 #TODO

2023-10-25 21:34 UTC, Shreya1233 requested changes
looks good for the most part! Just had a couple of comments here and there :)

2023-11-08 22:27 UTC, Shreya1233 approved these changes
Looks good to me!

2023-11-11 21:30 UTC, merged