Traverse directions
cornellnexus/src pull request #150
Opened 2023-11-04 23:30 UTC by jinlin270

## Summary
This PR enables traversal in UP, DOWN, LEFT, and RIGHT directions, rather than just UP and RIGHT directions. 

### Description
Previously the algorithm assumes to traverse in the UP or RIGHT direction, and user is allowed to choose between these 2 using the is_vertical traversal flag. The algorithm is added on slightly so the user can instead choose between 4 directions of traversal, and the find_border_node function is expanded to find the start traversal position to support the different cases.

## Test Plan

This can be tested by running:
python3 -m tests.functionality_tests.test_activation_shapes
for shapes, input one of [ triangle ;  circle ; rectangle ] as shapes (must be spelled correctly and in lower case)
for direction, input one of [UP , DOWN, LEFT, RIGHT]  (must be spelled correctly and in upper case) 

## Other

You can find what the test cases should look like inside 
'src/tests/functionality_tests/activate_shape_graphs'
![Uploading left_circle.png…]()

2023-11-05 20:56 UTC, AC408 commented on tests/functionality_tests/activate_shape_graphs/up_triangle.png
Is this meant to still be broken?

2023-11-05 20:56 UTC, AC408 commented on tests/functionality_tests/activate_shape_graphs/down_triangle.png
bottom left looks messed up

2023-11-05 20:57 UTC, AC408 commented on engine/grid.py
> +                    top_right_pos = (r_row, col)
I dont think this works if the shape is wide on the bottom and narrow at the top (like a triangle)

2023-11-05 21:00 UTC, AC408 commented on engine/grid.py
> +        bottom_left_pos = None
alternative solution is to DFS and keep track of bottom left, bottom right, top left, top right. we should also define "bottom_left", "bottom_right", "top_left", and "top_right" for future purposes if we have an irregular shape (think diamond)

2023-11-05 21:01 UTC, AC408 commented on engine/grid.py
> +            self.direction = self.Direction.RIGHT
might be better to have `elif direction == "RIGHT"` and then have an else condition that throws an error

2023-11-05 21:02 UTC, AC408 commented on tests/functionality_tests/test_activation_shapes.py
> +        grid.direction = grid.Direction.LEFT
same as above, probably better to have elif and else and throw error

2023-11-05 21:02 UTC, AC408 commented on tests/functionality_tests/test_activation_shapes.py
> +    print(direction)
add debug state

2023-11-05 21:03 UTC, AC408 commented on tests/functionality_tests/test_activation_shapes.py
> +    print(direction)
and add additional print text for better clarification

2023-11-05 21:04 UTC, AC408 commented on tests/functionality_tests/test_activation_shapes.py
> +        way_points = grid.get_all_guided_lawnmower_waypoints_adjustable(direction)
grid.find_border_node() and waypoints = ... can be moved outside of if statements to reduce duplicate code

2023-11-05 21:04 UTC, AC408 requested changes
a few comments

2023-11-18 18:27 UTC, jinlin270 commented on tests/functionality_tests/activate_shape_graphs/up_triangle.png
yep

2023-11-18 18:43 UTC, jinlin270 commented on tests/functionality_tests/activate_shape_graphs/up_triangle.png
Up and Down for triangle are not working

2023-11-29 23:42 UTC, closed without merging