New Packet Making Implementation Using Robot and Mission States
cornellnexus/src pull request #161
Opened 2023-12-02 01:40 UTC by Shreya1233

## References

## Summary
### TLDR: This is our new packet making implementation in our transmittor file that replaces the packet making implementation in our database file. The packet making implementation uses robot and mission state attributes to define values of the packet unlike the previous packet making implementation. 

### Description

Using the packet description defined by Sammie last semester (https://github.com/cornellnexus/src/blob/main/engine/packet.md), we no longer need the Packet class or the make_packet implementation in the Database class. There is an additional test case named transmission_test to test the validity of this new packet making implementation. 

## Test Plan

python3 -m tests.compilation_tests.test_runner
python3 -m engine.main

## Other

2023-12-02 02:18 UTC, AC408 approved these changes
looks good!

2024-03-02 18:06 UTC, jinlin270 approved these changes

2024-03-02 18:11 UTC, jinlin270 requested changes
need to rebase first

2024-03-02 18:32 UTC, jinlin270 approved these changes

2024-03-23 18:10 UTC, merged