Integrate motor controller
cornellnexus/src pull request #93
Opened 2022-10-15 18:08 UTC by yagmurdulger

Prior to this PR, our `move_to_target_node` and `turn_to_target_heading` functions weren't integrated with the electrical `motor_controller` code, and so, all movement was simulated. With these changes:
- Robot class is able to call `spin_motors` function with the desired (clamped) linear and angular velocities as parameters
- The motor controller then converts this information into different voltages that should be applied to the left and right motors for desired movement.
- Additionally, we now initialize `motor_controller` in `Robot` rather than `Mission` which enables the above functionality.

2022-10-15 18:49 UTC, juliehelenek commented on engine/mission.py
> +        if self.robot.is_sim:
should be if not self.robot.is_sim

2022-10-15 18:49 UTC, juliehelenek commented on engine/mission.py
> +                self.robot.execute_setup(
is the spacing weird when u open in vs code?

2022-10-15 18:49 UTC, juliehelenek commented on engine/robot.py
> +        if not self.is_sim:
do we still want to initialize one when we don't have a simulation?

2022-10-15 18:49 UTC, juliehelenek commented on engine/robot.py
> +        if not self.is_sim:
why are we only initializing one if its not a simulation, but then later in robot.py we only use the motorcontroller if it IS a simulation?

2022-10-19 15:08 UTC, angelaloh09 requested changes
some small changes to be made!

2022-10-28 16:47 UTC, angelaloh09 approved these changes
looks good to me

2022-10-28 16:48 UTC, merged